
require(dplyr)

source("factor.data.frame.R")

TL <- list(
    region = paste(
        "NTNU;   REMIND",
        "AME;    AFR",
        "CN;     CHN",
        "RER;    EUR",
        "IN;     IND",
        "PAC;    JPN",
        "LA;     LAM",
        "AME;    MEA",
        "AS;     OAS",
        "PAC;    ROW",
        "EIT;    RUS",
        "US;     USA",
        sep = "\n"),

    scenario = paste(
        "NTNU;       REMIND;                                  legend",
        "Baseline;   ADV_WP5_Base;                            Baseline",
        "BLUE_Map;   ADV_WP5_P240_FullTech_direct_only;       direct only",
        "BLUE_Map;   ADV_WP5_P240_FullTech;                   Policy",
        "BLUE_Map;   ADV_WP5_P240_FullTech_hydroCH4;          hydro CH4",
        "BLUE_Map;   ADV_WP5_P240_FullTech_full_accounting;   full accounting",
        "BLUE_Map;   ADV_WP5_P240_LimVRE;                     Conv",
        "BLUE_Map;   ADV_WP5_P240_NoCCSNucPO;                 Ren",
        "BLUE_Map;   ADV_WP5_P240_LimVRENucPO;                CCS",

        sep = "\n"),

    scenario.advance = paste(
       "NTNU;       ADVANCE_dyn;                  ADVANCE_stat;               legend",
       "Baseline;   ADV_WP5_Base_dyn;             ADV_WP5_Base;               Base",
       "BLUE_Map;   ADV_WP5_P240_FullTech_dyn;    ADV_WP5_P240_FullTech;      FullTech",
       "BLUE_Map;   ADV_WP5_P240_LimVRE_dyn;      ADV_WP5_P240_LimVRE;        LimVRE",
       "BLUE_Map;   ADV_WP5_P240_NoCCSNucPO_dyn;  ADV_WP5_P240_NoCCSNucPO;    NoCCSNucPO",
       "BLUE_Map;   ADV_WP5_P240_LimVRENucPO_dyn; ADV_WP5_P240_LimVRENucPO;   LimVRENucPO",
       sep = "\n"),


    impact.names.LCA = paste(
        "impact;                      colour;    legend",
        "Climate change;              #111111;    Clim. change ",
        "Particulate matter;          #111111;    PM-10",
        "Human toxicity;              #e31a1c;    Human tox.",
        "Ionising radiation;          #FFFF00;    Ionizing rad.",
        "Oxidant formation;           #FF8C00;    Oxidant form.",
        "Ozone depletion;             #6a3d9a;    O3 depl.",
        "Natural land transformation; #8B4513;    Nat. land transformation",
        "Agricultural and urban land occupation; #33a02c; Land occ.",
        "Terrestrial acidification;   #eeCC00;   Terr. acid.",
        "Terrestrial ecotoxicity;     #b2df8a;   Terr. ecotox.",
        "Freshwater ecotoxicity;      #fb9a99;   FrWat. ecotox.",
        "Marine ecotoxicity;          #cab2d6;   Marine ecotox.",
        "Mineral resource depletion;  #dd7000;   Mineral resource depletion",
        "Freshwater eutrophication;   #e31a1c;    FrWat. eutro.",
        "Fossil depletion;            #555555;    Fossils",
        "Metal depletion;             #dd7000;    Minerals",
        "Water Withdrawal;             #dd7000;    Water withdrawal",

        sep = "\n"),


    technology = paste(
        "NTNU;             REMIND",
        "Coal w CCS;       Coal|w/ CCS",
        "Coal wo CCS;      Coal|w/o CCS",
        "NA;               Oil",
        "Nuclear;          Nuclear",
        "Gas w CCS;        Gas|w/ CCS",
        "Gas wo CCS;       Gas|w/o CCS",
        "Bio w CCS;        Biomass|w/ CCS",
        "Bio wo CCS;       Biomass|w/o CCS",
#         "Bio w CCS;        Biomass|no cogen.|w/ CCS",
#         "Bio wo CCS;       Biomass|no cogen.|w/o CCS",
        "Wind, onshore;    Wind",
        "Wind, offshore;   NA",
        "Hydro;            Hydro",
        "CSP;              Solar|CSP",
        "PV;               Solar|PV",
        "Storage;          Storage",
        # "Grid;             Grid",
        "Base Grid;        Base Grid",
        "VRE Grid;         VRE Grid",
        sep = "\n"),

   model.names = paste(
      "full;            short",
      "GCAM;            GCAM",
      "IMAGE 3.0;       IMAGE",
      "MESSAGE-GLOBIOM_1.0;  MESSAGE",
      "POLES ADVANCE;   POLES",
      "REMIND 1.7;      REMIND",
      "WITCH 2014;      WITCH" ,
      sep = "\n"),

    technology.names = paste(
        "REMIND;            legend;            colour",
        "Coal|w/o CCS;      Coal w/o CCS;      #101010",
        "Coal|w/ CCS;       Coal w/ CCS;       #b2b2b2",
        "Oil;               Oil;               #804020",
        "Gas|w/o CCS;       Gas w/o CCS;       #999959",
        "Gas|w/ CCS;        Gas w/ CCS;        #e5e5b2",
        "Nuclear;           Nuclear;           #ff33ff",
        "Hydro;             Hydropower;        #191999",
        "Biomass|w/o CCS;   Bio w/o CCS;   #005900",
        "Biomass|w/ CCS;    Bio w/ CCS;    #33ff00",
#        "Biomass irrigation; Bio irrig.  ; #00ffcc",
#         "Biomass|no cogen.|w/o CCS;      Biomass (no cogen.) w/o CCS;   #005900",
#         "Biomass|no cogen.|w/ CCS;       Biomass (no cogen.) w/ CCS;    #33ff00",
#         "Biomass|cogeneration|w/o CCS;   Biomass (cogen.) w/o CCS;      #00b000",
#         "Biomass|cogeneration|w/ CCS;    Biomass (cogen.) w/ CCS;       #a1ff89",
        "Geothermal;        Geothermal;        #900000",
        "Wind;              Wind;              #337fff",
#        "Wind farm;              Wind farm;      #77afff",
        "Solar|CSP;         CSP;               #ff8000",
        "Solar|PV;          PV;                #ffcc00",
        sep = "\n"),

technology.names.LCA = paste(
    "IAMC;                 legend;         colour",
    "Coal|w/o CCS;         Coal w/o CCS;   #101010",
    "Coal|w/ CCS;          Coal w/ CCS;    #b2b2b2",
#    "Oil;                  Oil;            #804020",
    "Oil|w/o CCS;          Oil w/o CCS;    #804020",
    "Oil|w/ CCS;           Oil w/ CCS;     #deb887",
    "Gas|w/o CCS;          Gas w/o CCS;    #999959",
    "Gas|w/ CCS;           Gas w/ CCS;     #e5e5b2",
    "Nuclear;              Nuclear;        #ff33ff",
    "Hydro;                Hydropower;     #191999",
    "Biomass|w/o CCS;      Bio w/o CCS;    #005900",
    "Biomass|w/ CCS;       Bio w/ CCS;     #33ff00",
    "Biomass irrigation;   Bio irrigation;     #00ffcc",
    "Geothermal;           Geothermal;     #900000",
    "Wind;                 Wind;           #337fff",
    "Wind farm;            Wind farm;      #77afff",
    "Solar|CSP;            CSP;            #ff8000",
    "Solar|PV;             PV;             #ffcc00",
    "Storage;              Storage;        #eac0d5",
    "Grid;                 Grid;           #c0ead2",
    "Base Grid;            Base Grid;      #c0ead2",
    "VRE Grid;             VRE Grid;       #c0ea69",
    sep = "\n"),





    lifetime = paste(
        "technology;                     REMIND",
        "Coal|w/o CCS;                   40",
        "Coal|w/ CCS;                    40",
        "Gas|w/o CCS;                    35",
        "Gas|w/ CCS;                     35",
        "Biomass|no cogen.|w/o CCS;      40",
        "Biomass|no cogen.|w/ CCS;       40",
        "Biomass|cogeneration|w/o CCS;   40",
        "Biomass|cogeneration|w/ CCS;    40",
        "Biomass|w/o CCS;                40",
        "Biomass|w/ CCS;                 40",
        "Nuclear;                        40",
        "Hydro;                          70",
        "Wind;                           25",
        "Wind|Onshore;                   25",
        "Wind|Offshore;                  25",
        "Solar|CSP;                      30",
        "Solar|PV;                       30",
        sep = "\n"),

    load.factor = paste(
        "technology;                     nu",
        "Coal|w/o CCS;                   0.75",
        "Coal|w/ CCS;                    0.75",
        "Gas|w/o CCS;                    0.85",
        "Gas|w/ CCS;                     0.6",
        "Biomass|w/o CCS;                0.6",
        "Biomass|w/ CCS;                 0.8",
        "Biomass|no cogen.|w/o CCS;      0.6",
        "Biomass|no cogen.|w/ CCS;       0.8",
        "Biomass|cogeneration|w/o CCS;   0.6",
        "Biomass|cogeneration|w/ CCS;    0.8",
        "Nuclear;                        0.8",
        "Hydro;                          1",
        "Wind;                           1",
        "Wind|Onshore;                   1",
        "Wind|Offshore;                  1",
        "Solar|CSP;                      1",
        "Solar|PV;                       1",
        sep = "\n"),

    self_specific = paste(
        "self.energy.consumption;   specific.energy.input",
        "Cement;                    Cement and concrete",
        "Freight transportation;    Freight transportation",
        "Iron;                      Iron and steel",
        sep = "\n"),

    self_specific.units = paste(
        "self.unit;   specific.unit",
        "t;      t_iron",
        "t;      t_cement",
        "tkm;    tkm",
        sep = "\n")
)

TL <- lapply(TL,
             function(x) {
                     read.table(textConnection(x), header = TRUE, sep = ";",
                                na.strings = "NA", strip.white = TRUE,
                                stringsAsFactors = TRUE, comment.char = "")
             })

impact_order = c("Aluminium",
                 "Cement",
                 "Copper",
                 "Particulate matter",
                 "Particulate matter formation",
                 "Photochemical oxidant formation",
                 "Oxidant formation",
                 "Terrestrial acidification",
                 "Terrestrial acidification2",
                 "Freshwater ecotoxicity",
                 "Terrestrial ecotoxicity",
                 "Marine ecotoxicity",
                 "Ecotoxicity",
                 "Freshwater eutrophication",
                 "Human toxicity",
                 "Ionising radiation",
                 "Iron",
                 "Land occupation",
                 "Natural land transformation",
                 "Deforestation",
                 "Marine eutrophication",
                 "Metal depletion",
                 "Mineral resource depletion",
                 "Fossil depletion",
                 "Water Withdrawal", "Water Consumption",
                 "CO2 storage",
                 "Water Withdrawal",
                 "Water Consumption",
                 "GHG (excl. CDR)",
                 "direct NOx",
                 "direct Sulfur",
                 "VOC",
                 "NOx",
                 "Sulfur",
                 "BC",
                 "CO",
                 "OC",
                 "Ecosystem|Terrestrial ecotoxicity",
                 "Ecosystem|Marine ecotoxicity",
                 "Ecosystem|Freshwater ecotoxicity",
                 "Ecosystem",
                 "HumanHealth",
                 "Resource")


    impact.names = matrix(c(
        "Climate change", "              #111111", "Clim. change ",
        "Particulate matter", "          #111111", "PM-10",
        "Human toxicity", "              #e31a1c", "Human tox.",
        "Ionising radiation", "          #FFFF00", "Ionizing\nradiation",
        "Oxidant formation", "           #FF8C00", "Oxidant\nformation",
        "Ozone depletion", "             #6a3d9a", "O3 depl.",
        "Natural land transformation", " #8B4513", "Nat. land\ntransformation",
        "Agricultural and urban land occupation", " #33a02c", "Land\noccupation",
        "Land occupation", " #33a02c", "Land\noccupation",
        "Terrestrial acidification", "   #eeCC00", "Terr. acid.",
        "Terrestrial ecotoxicity", "     #b2df8a", "Terr. ecotox.",
        "Freshwater ecotoxicity", "      #fb9a99", "Freshwater\necotox.",
        "Marine ecotoxicity", "          #cab2d6", "Marine\necotox.",
        "Mineral resource depletion", "  #dd7000", "Mineral\nresource depletion",
        "Freshwater eutrophication", "   #e31a1c", "Freshwater\neutrophication",
        "Marine eutrophication", "   #e31a1c", "Marine\neutrophication.",
        "Fossil depletion", "            #555555", "Fossils",
        "Metal depletion", "             #dd7000", "Minerals",
        "Water Withdrawal", "             #dd7000", "Water\nwithdrawal"),
        nrow = 3, dimnames = list(c("impact","color", "label")))

    impact.names <- impact.names %>% t() %>% as.data.frame()

